name: README update

on:
  push:
    branches:
      - main
  
permissions:
  contents: write

jobs:
  run-code:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install beautifulsoup4
          
      - name: Run Python script
        run: python README.py
        
      - name: Commit and push changes
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "Update README.md"
          git push https://${{ secrets.GH_TOKEN }}@github.com/ykdy3951/LeetCode.git HEAD:main
